/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.masterclinic.VISTA;

import com.masterclinic.CONTROLADOR.EnvioDatosPHP;
import com.masterclinic.CONTROLADOR.GestionAcortadorURL;
import com.masterclinic.CONTROLADOR.GestionSMS;
import com.masterclinic.CONTROLADOR.ObtencionDatos;
import com.masterclinic.MODELO.Cita;
import com.masterclinic.MODELO.DatosGlobales;
import com.masterclinic.MODELO.Url;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gott Jagger
 */
public class CitaMedicaGUI extends javax.swing.JFrame {

    /**
     * Creates new form CitaMedicaGUI
     */
    public CitaMedicaGUI() {
        new Thread(new GestionJava()).start();
        this.estadoPHP = new Vector();
        this.estadoAcURL = new Vector();
        this.estadoSMS = new Vector();

        datosCitas = datos.llenarCita(datos.extraerDatosCita());

        initComponents();

    }

    private class GestionJava implements Runnable {

        @Override
        public void run() {

            while (true) {
                try {
                    Calendar calendario = Calendar.getInstance();
                    int hora, minuto, segundos;
                    hora = calendario.get(Calendar.HOUR_OF_DAY);
                    minuto = calendario.get(Calendar.MINUTE);
                    segundos = calendario.get(Calendar.SECOND);

                    if (hora == 9 && minuto == 49 && segundos == 0) {
                        estadoAcURL.clear();
                        estadoPHP.clear();
                        estadoSMS.clear();

                        GestionAcortadorURL acortardorUrl = new GestionAcortadorURL();
                        EnvioDatosPHP expedidorDatosCitas = new EnvioDatosPHP();
                        GestionSMS gestorSMS = new GestionSMS();

                        datosAcURL = acortardorUrl.AcortarURL(acortardorUrl.ExtraerURL(datosCitas),
                                estadoAcURL);
                        expedidorDatosCitas.RequestPHP(datosCitas, datosAcURL, estadoPHP);
                        gestorSMS.CrearSMS(datosCitas, datosAcURL, estadoSMS);

                        Thread.sleep(3000);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(CitaMedicaGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Paciente", "Telefono", "Empresa", "Entidad", "Medico", "Tipo Consulta", "Observacion", "Fecha", "Estado URL", "Estado SMS", "Estado PHP"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Generar Citas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado de Envio.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1156, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "ID", "Paciente", "Telefono", "Empresa", "Entidad", "Medico",
                    "Tipo Consulta", "Observacion", "Fecha", "Estado URL",
                    "Estado SMS", "Estado PHP"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();

        if (estadoAcURL.size() == 0 && estadoPHP.size() == 0 && estadoSMS.size() == 0 && flag == false) {
            for (int i = 0; i < datosCitas.size(); i++) {
                estadoAcURL.add("no se ha acortado");
                estadoPHP.add("no se ha guardado");
                estadoSMS.add("no se ha enviado");
            }
            flag = true;

        }
        for (int i = 0; i < datosCitas.size(); i++) {
            Object[] data = {datosCitas.get(i).getId(),
                datosCitas.get(i).getPaciente(), datosCitas.get(i).getTelefono(),
                datosCitas.get(i).getEmpresa(), datosCitas.get(i).getEntidad(),
                datosCitas.get(i).getMedico(), datosCitas.get(i).getTipo_consulta(),
                datosCitas.get(i).getObservaciones(), datosCitas.get(i).getFecha(),
                estadoAcURL.elementAt(i), estadoSMS.elementAt(i), estadoPHP.elementAt(i)};
            modelo.addRow(data);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitaMedicaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitaMedicaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitaMedicaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitaMedicaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new CitaMedicaGUI().setVisible(true);

            }
        });
    }

    Vector<String> estadoPHP;
    Vector<String> estadoAcURL;
    Vector<String> estadoSMS;
    boolean flag = false;

    ObtencionDatos datos = new ObtencionDatos();
    ArrayList<Cita> datosCitas;
    ArrayList<Url> datosAcURL;
    private javax.swing.JDialog jAlert;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
